name = "my-preset"

[config]
clip_guidance_scale = 30000
tv_scale = 0.0
range_scale = 20000.0
sat_scale = 34523.80952380953
clamp_max = 0.05
cutn_batches = 4
eta = 0.8
perlin_init = false
cut_overview = "[12]*400+[4]*600"
cut_innercut = "[4]*400+[12]*600"
cut_ic_pow = "[1]*1000"
cut_icgray_p = "[0.2]*400+[0]*600"

[models]
clip_models = ["RN50", "ViT-B/32", "ViT-B/16"]
use_secondary_model = true
